-- MIQ Smart Assessment System - Schema SQL
-- Berdasarkan PRD Fase 4 (Database Design & ERD)

-- Enable pgcrypto for UUID generation if needed (Supabase usually has this by default)
-- CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-------------------------------------------------------------------
-- 1. PROFILES TABLE
-------------------------------------------------------------------
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('super_admin', 'admin', 'examiner', 'leader')),
  status BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profile Policies
CREATE POLICY "Users can view their own profile." ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles." ON public.profiles FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('super_admin', 'admin'))
);
-- Additional policies for insert/update can be added for admin

-------------------------------------------------------------------
-- 2. LEVELS TABLE
-------------------------------------------------------------------
CREATE TABLE public.levels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  prefix TEXT,
  sort_order INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true
);

ALTER TABLE public.levels ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Levels are viewable by everyone." ON public.levels FOR SELECT USING (true);

-------------------------------------------------------------------
-- 3. CLASSES TABLE
-------------------------------------------------------------------
CREATE TABLE public.classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level_id BIGINT REFERENCES public.levels(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  active BOOLEAN DEFAULT true
);

ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Classes are viewable by everyone." ON public.classes FOR SELECT USING (true);

-------------------------------------------------------------------
-- 4. STUDENTS TABLE
-------------------------------------------------------------------
CREATE TABLE public.students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT REFERENCES public.classes(id) ON DELETE RESTRICT,
  full_name TEXT NOT NULL,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Students are viewable by everyone." ON public.students FOR SELECT USING (true);
CREATE INDEX idx_students_class_id ON public.students(class_id);

-------------------------------------------------------------------
-- 5. EXAM PERIODS & TYPES
-------------------------------------------------------------------
CREATE TABLE public.exam_periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  active BOOLEAN DEFAULT true
);

CREATE TABLE public.exam_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

ALTER TABLE public.exam_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Exam periods are viewable by everyone." ON public.exam_periods FOR SELECT USING (true);
CREATE POLICY "Exam types are viewable by everyone." ON public.exam_types FOR SELECT USING (true);

-------------------------------------------------------------------
-- 6. CRITERIA TABLE
-------------------------------------------------------------------
CREATE TABLE public.criteria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  default_score NUMERIC NOT NULL,
  deduction NUMERIC NOT NULL,
  sort_order INTEGER DEFAULT 0,
  active BOOLEAN DEFAULT true
);

ALTER TABLE public.criteria ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Criteria are viewable by everyone." ON public.criteria FOR SELECT USING (true);

-------------------------------------------------------------------
-- 7. SCORE SESSIONS TABLE
-------------------------------------------------------------------
CREATE TABLE public.score_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  examiner_id UUID REFERENCES public.profiles(id) ON DELETE RESTRICT,
  class_id BIGINT REFERENCES public.classes(id) ON DELETE RESTRICT,
  period_id BIGINT REFERENCES public.exam_periods(id) ON DELETE RESTRICT,
  exam_type_id BIGINT REFERENCES public.exam_types(id) ON DELETE RESTRICT,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  finished_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.score_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Examiners can view their own sessions." ON public.score_sessions FOR SELECT USING (auth.uid() = examiner_id);
CREATE POLICY "Admins can view all sessions." ON public.score_sessions FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('super_admin', 'admin'))
);
CREATE POLICY "Examiners can create sessions." ON public.score_sessions FOR INSERT WITH CHECK (auth.uid() = examiner_id);

-------------------------------------------------------------------
-- 8. SCORES & SCORE DETAILS
-------------------------------------------------------------------
CREATE TABLE public.scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES public.score_sessions(id) ON DELETE RESTRICT,
  student_id BIGINT REFERENCES public.students(id) ON DELETE RESTRICT,
  total_score NUMERIC NOT NULL,
  grade TEXT,
  notes TEXT,
  locked BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  -- Constraint: 1 Santri, 1 Periode, 1 Jenis Ujian = 1 Nilai (BR-001)
  -- Untuk level database, kita asumsikan kombinasi session_id dan student_id sudah cukup unik
  -- Atau bisa dibuat kolom bantuan period_id + exam_type_id untuk unique constraint
  UNIQUE(session_id, student_id) 
);

CREATE TABLE public.score_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  score_id BIGINT REFERENCES public.scores(id) ON DELETE CASCADE,
  criteria_id BIGINT REFERENCES public.criteria(id) ON DELETE RESTRICT,
  mistakes INTEGER NOT NULL,
  score NUMERIC NOT NULL
);

ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.score_details ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_scores_student_id ON public.scores(student_id);
CREATE INDEX idx_scores_session_id ON public.scores(session_id);
CREATE INDEX idx_score_details_score_id ON public.score_details(score_id);

-- Simple RLS for Scores
CREATE POLICY "Scores viewable by admins and respective examiner." ON public.scores FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('super_admin', 'admin')) OR
  EXISTS (SELECT 1 FROM public.score_sessions ss WHERE ss.id = session_id AND ss.examiner_id = auth.uid())
);
CREATE POLICY "Examiners can insert scores." ON public.scores FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.score_sessions ss WHERE ss.id = session_id AND ss.examiner_id = auth.uid())
);
CREATE POLICY "Examiners can update unlocked scores." ON public.scores FOR UPDATE USING (
  locked = false AND EXISTS (SELECT 1 FROM public.score_sessions ss WHERE ss.id = session_id AND ss.examiner_id = auth.uid())
);

-------------------------------------------------------------------
-- 9. EXAMINER ASSIGNMENTS
-------------------------------------------------------------------
CREATE TABLE public.examiner_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  examiner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
  period_id BIGINT REFERENCES public.exam_periods(id) ON DELETE CASCADE
);

ALTER TABLE public.examiner_assignments ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_assignments_examiner_id ON public.examiner_assignments(examiner_id);

CREATE POLICY "Examiners can view their own assignments." ON public.examiner_assignments FOR SELECT USING (auth.uid() = examiner_id);
CREATE POLICY "Admins can view all assignments." ON public.examiner_assignments FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('super_admin', 'admin'))
);
