-- Deprecated compatibility entrypoint.
--
-- Kebijakan RLS lama di file ini sebelumnya terlalu longgar untuk tabel
-- scores dan score_details. Untuk hardening P0 terbaru, jalankan:
--
--   supabase/migrations/01_p0_security_fixes.sql
--
-- File ini sengaja tidak membuat policy apa pun agar tidak membuka ulang
-- akses nilai lintas penguji.
